language: node_js
node_js: 
  - 14.8.0
cache: yarn

# before_install:
install:
  - yarn install

# before_script:
script:
  - yarn test
  - yarn run build

# after_success:
# after_failure:

# before_deploy:
deploy:
  provider: azure_web_apps
# after_deploy: